image: python:3.10
default:
    tags:
      - docker
stages:
  - test

before_script:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install black

test:linting:
  script:
    - black ./

test:app_run:
  script:
    - streamlit run NanoPrepare.py
